# Generated by Django 4.0 on 2023-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sites_graphics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='sites',
            name='graphics',
        ),
    ]
